# -*- coding: utf-8 -*-
"""final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9kdT9YhnFDr0yBDkWkE_7J_Ufysvig6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

VALID_CATEGORIES = ["Food", "Transport", "Utilities", "Entertainment", "Health", "Shopping"]
class Expense_Tracker:
  def __init__(self):
    self.date=None
    self.amount=None
    self.category=None
    self.description=None
    self.data=None


  def load_data(self):
    if self.data is not None:
      print("\nDataset already loaded.")
      return
    else:
        try:
          file_path=input("\nEnter the file path to load dataset:\n ")
          self.data=pd.read_csv(file_path)
          print(self.data.head())
        except FileNotFoundError:
          print("\nFile not found. Please check the file path and try again.")
        except Exception as e:
          print(f"\nAn error occurred while loading the dataset: {e}")

  def add_expence(self,date,amount,category,description):
    if self.data is None:
      print("\nPlease load the dataset first.")
      return
    else:
      if amount <= 0:
            print(" Amount must be positive!")
            return

      if category not in VALID_CATEGORIES:
            print(" Invalid category! Choose from:", VALID_CATEGORIES)
            return

      new_expense = {
          "Date": date,
          "Amount": amount,
          "Category": category,
          "Description": description
          }

      self.data=pd.concat([self.data,pd.DataFrame([new_expense])],ignore_index=True)
      print("\nNew Expence added Succesfully")
      print(self.data.tail())


  def get_summary(self):
    if self.data is None:
      print("\nPlease load the dataset first.")
      return
    else:
      print("Summary of Data:")
      print("1.basic information")
      print("2.Data Types")
      print("3.Missing Values")
      print("4.Summary Statistics")
      print("5.Total amount of expenses")
      print("6.Average Spending")

      choice=int(input("Enter your choice: "))

      match choice:
        case 1:
          print("\n Basic Information:")
          print(self.data.info())
        case 2:
          print("\n Data Types:")
          print(self.data.dtypes)
        case 3:
          print("choose option:")
          print("1.Check Missing Values")
          print("2.Replace Missing Values with mean")
          print("3.drop missing value")
          print("4.replace missing values with specific value")

          sub_choice=int(input("Enter your choice: "))

          if sub_choice==1:
            data_missing=self.data.isnull().sum()
            if data_missing.any():
              print("\nMissing Values:")
              print(data_missing)
            else:
              print("\nNo missing values in the dataset.")
          elif sub_choice==2:
            data_missing=self.data.isnull().sum()
            if data_missing is None:
              print("\nNo missing values in the dataset.")
            else:
              mean_values = self.data.mean(numeric_only=True)
              print("\Replacing Missing Values with mean:")
              self.data.fillna(mean_values,inplace=True)
              print(self.data.info())
          elif sub_choice==3:
            data_missing=self.data.isnull().sum()
            if data_missing is None:
              print("\n No missing values in the dataset.")
            else:
              print("\nDropping Missing Values:")
              self.data.dropna(inplace=True)
              print(self.data.info())
          elif sub_choice==4:
            data_missing=self.data.isnull().sum()
            if data_missing is None:
              print("\nNo missing values in the dataset.")
            else:
              print("\nReplacing Missing Values with specific value:")
              value=int(input("Enter the value to replace missing values: "))
              self.data.fillna(value,inplace=True)
              print(self.data.info())
          else:
            print("Invalid choice")
        case 4:
          print("\nSummary Statistics:")
          print(self.data.describe())
        case 5:
          total_amount=self.data["Amount"].sum()
          print(f"\nTotal amount of expenses: {total_amount}")
        case 6:
          average_spending=self.data["Amount"].mean()
          print(f"\nAverage Spending: {average_spending}")

  def filter_expences(self):
    col = input("Enter column: ")
    op = input("Enter operator (=, >, <): ")
    val = input("Enter value: ")

    if op == ">":
        print(self.data[self.data[col] > float(val)])
    elif op == "<":
        print(self.data[self.data[col] < float(val)])
    elif op == "=":
        print(self.data[self.data[col] == val])
    else:
        print("Invalid operator")



  def generate_report(self):
    print("\n------ REPORT ------")
    print("Top Spending Categories:")
    print(self.data.groupby("Category")["Amount"].sum().sort_values(ascending=False))

    print("\nMonthly Spending:")
    self.data["Date"] = pd.to_datetime(self.data["Date"])
    print(self.data.groupby(self.data["Date"].dt.month)["Amount"].sum())

  def plot_category_expenses(self):

    plt.figure(figsize=(7,5))
    self.data.groupby("Category")["Amount"].sum().plot(kind="bar")
    plt.title("\nTotal Expenses by Category\n")
    plt.xlabel("Category")
    plt.ylabel("Amount")
    plt.show()

  def plot_trend(self):
    plt.figure(figsize=(7,5))
    self.data["Date"] = pd.to_datetime(self.data["Date"])
    plt.plot(self.data["Date"], self.data["Amount"])
    plt.title("Expense Trend Over Time")
    plt.xlabel("Date")
    plt.ylabel("Amount")
    plt.show()


  def plot_pie(self):
    self.data.groupby("Category")["Amount"].sum().plot(kind="pie", autopct="%1.1f%%")
    plt.title("Spending Distribution")
    plt.ylabel("")
    plt.show()


  def plot_hist(self):
    plt.figure(figsize=(7,5))
    sns.histplot(self.data["Amount"], bins=10)
    plt.title("Expense Amount Distribution")
    plt.xlabel("Amount")
    plt.ylabel("Frequency")
    plt.show()

  def plot_category_boxplot(self):
    plt.figure(figsize=(8,6))
    sns.boxplot(x="Category", y="Amount", data=self.data)
    plt.title("Expense Distribution by Category")
    plt.xlabel("Category")
    plt.ylabel("Amount")
    plt.xticks(rotation=45)
    plt.show()

  def main(self):
    while True:
        print("Welcome to Expense Tracker")
        print("1: Load Data")
        print("2: Add Expense")
        print("3: Get Summary")
        print("4: Filter Expenses")
        print("5: Generate Report")
        print("6.Exit")

        choice=int(input("Enter your choice: "))

        match choice:
          case 1:
            self.load_data()
          case 2:
            date=input("Enter the date: ")
            amount = float(input("Enter amount: "))
            category = input(f"Enter category {VALID_CATEGORIES}: ")
            desc = input("Enter description: ")
            self.add_expence(date,amount,category,desc)
          case 3:
            self.get_summary()
          case 4:
            self.filter_expences()
          case 5:
            self.generate_report()
            print("Plots:")
            self.plot_category_expenses()
            self.plot_trend()
            self.plot_pie()
            self.plot_hist()
            self.plot_category_boxplot()
          case 6:
            print("Exiting Expense Tracker")
            break
          case _:
            print("Invalid choice")

obj=Expense_Tracker()
obj.main()